name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-11

    steps:
    - name: Setup Xcode version
      uses: maxim-lobanov/setup-xcode@v1.2.3
      with:
        xcode-version: latest
    - name: Build
      run: xcodebuild clean test -project "GHRepos.xcodeproj" -scheme "GHRepos" -destination "platform=iOS Simulator,name=iPhone 12,OS=15.0"
    - name: Run tests
      run: xcodebuild -project "GHRepos.xcodeproj" -scheme "GHRepos" -destination "generic/platform=iOS" -configuration Release build CODE_SIGNING_ALLOWED=NO
