name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Switch to Xcode 12
      run: sudo xcode-select -s /Applications/Xcode_12.app/Contents/Developer
    - name: Build
      run: xcodebuild clean test -project "CombineDemo.xcodeproj" -scheme "CombineDemo" -destination "platform=iOS Simulator,name=iPhone 11 Pro,OS=14.0"
    - name: Run tests
      run: xcodebuild -project "CombineDemo.xcodeproj" -scheme "CombineDemo" -destination "generic/platform=iOS" -configuration Release build CODE_SIGNING_ALLOWED=NO
